const audioData = [
  { id: 1, title: "حسين قتيل في وادي طفوف", reciter: "باسم الكربلائي ", poet: " مهدي جناح الكاظمي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf.mp3" },
  { id: 2, title: "طفلة وشفت بل نوم", reciter: "باسم الكربلائي", poet: "  جابر الكاظمي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf2.mp3" },
  { id: 3, title: "باب الساعات", reciter: " سيد سلام الحسيني", poet: "أحمد اللامي ", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf3.mp3" },
  { id: 4, title: "شخبار اهلنه", reciter: " محمد الجنامي", poet: "السيد عبد الخالق المحنة", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf4.mp3" },
  { id: 5, title: " خطار اجاني", reciter: " باسم الكربلائي", poet: "   السيد سعيد الصافي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf5.mp3" },
  { id: 6, title: "  قارورة", reciter: " باسم الكربلائي", poet: " أحمد الذهبي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf6.mp3" },
  { id: 7, title: "  حنيت الك", reciter: " سيد فاقد ", poet: "  سيد محمد الموسوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf7.mp3" },
  { id: 8, title: "مانعوفك ", reciter: " باسم الكربلائي", poet: " جابر الكاظمي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf8.mp3" },
  { id: 9, title: "  يمة اطمنج علية", reciter: " باسم الكربلائي", poet: " إيهاب المالكي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf9.mp3" },
  { id: 10, title: "لا ترد ماضل اثر كلشي انتهه بسفركم", reciter: " باسم الكربلائي", poet: " السيد عبد الخالق المحنة", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf10.mp3" },
  { id: 11, title: "  زينب لفت", reciter: " باسم الكربلائي", poet: " السيد عبد الحسين الشرع", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf11.mp3" },
  { id: 12, title: " يخيمات ", reciter: " عمار الكناني", poet: " علي عويز الشوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf12.mp3" },
  { id: 13, title: "  مجنونك", reciter: " عمار الكناني ", poet: "حيدر تركي الكربلائي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf13.mp3" },
  { id: 14, title: "  يبني لو همك تريده ينجلي", reciter: " ملسم الوائلي", poet: "  علي أكبر الغرابي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf14.mp3" },
  { id: 15, title: "  ثاري الهجر ذباح", reciter: " سید سلام الحسيني", poet: " حيدر شايع", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf15.mp3" },
  { id: 16, title: "  ماضلت عيون (3دكات)", reciter: "كرار ابو غنيم", poet: " قحطان الحسناوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf16.mp3" },
  { id: 17, title: " وحدة حسين ", reciter: " كرار ابو غنيم", poet: " قحطان الحسناوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf17.mp3" },
  { id: 18, title: "3 دكات لا كمر لا ماي ", reciter: " كرار ابو غنيم", poet: " قحطان الحسناوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf18.mp3" },
  { id: 19, title: "  3دکات | یا فارس العلقمي", reciter: " زيد بقر الشام", poet: " أحمد زبول", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf19.mp3" },
  { id: 20, title: "  انه دامي", reciter: " مرتصى حرب", poet: " مرتضى حرب", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf20.mp3" },
  { id: 21, title: "  الحك يعباس", reciter: "حيدر سعد ", poet: " محمد الجماسي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf21.mp3" },
  { id: 22, title: "  رفت اول راية", reciter: " باسم الكربلائي", poet: " السيد معتز سلام الحسيني", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf22.mp3" },
  { id: 23, title: "  راحو راحو ياكلبي صحبانك مشو ", reciter: " سيد فاقد", poet: " حمزه الحسناوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf23.mp3" },
  { id: 24, title: " ابجيني مذبوح", reciter: " سيد قافد", poet: "حمزة الحسناوي ", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf24.mp3" },
  { id: 25, title: "تزوروني", reciter: " باسم الكربلائي", poet: " عبد الخالق المحنة", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf25.mp3" },
  { id: 26, title: "  يحسين بضمايرنا", reciter: "ياسين الرميثي", poet: "الشيخ عبد الحسين أبو شبع ", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf26.mp3" },
  { id: 27, title: "  جابر يجابر", reciter: "حمزة الصغير", poet: "كاظم منظور الكربلائي ", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf27.mp3" },
  { id: 28, title: "  أنا المظلوم عطشانا", reciter: " نزار القطري", poet: "جابر الكاظمي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf28.mp3" },
  { id: 29, title: " شلون أصبر على الآه", reciter: " باسم الكربلائي ", poet: "عبد الخالق المحنة", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf29.mp3" },
  { id: 30, title: "  مرت سنة ونص", reciter: " باسم الكربلائي", poet: " ميرزا عادل أشكناني", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf30.mp3" },
  { id: 31, title: "  التوبة", reciter: "سيد فاقد", poet: " علي مالك الموسوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf31.mp3" },
  { id: 32, title: "مثل طبع نسر طبعي  ", reciter: " باسم الكربلائي", poet: " جابر الكاظمي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf32.mp3" },
  { id: 33, title: "  ما حسبت هالكثر", reciter: " باسم الكربلائي", poet: " علي السقاي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf33.mp3" },
  { id: 34, title: " رجعنه اليسر ", reciter: " هادي المريطي", poet: "صباح امين", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf34.mp3" },
  { id: 35, title: " عظم اللة اجرك ", reciter: " احمد الفتلاوي", poet: " سيد هاشم العوادي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf35.mp3" },
  { id: 36, title: "  خلصت يا حرامات", reciter: "عمار الكناني", poet: "حسين طالب السماوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf36.mp3" },
  { id: 37, title: "  نزلة نجفية", reciter: " كرار العارضي", poet: "صباح امين", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf37.mp3" },
  { id: 38, title: " عينك يوفاي", reciter: "  كرار ابو غنيم", poet: "قحطان الحسناوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf38.mp3" },
  { id: 39, title: "  كل ما اشوفك", reciter: " باسم الكربلائي", poet: " السيد عبد الخالق المحنة", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf39.mp3" },
  { id: 40, title: "  يغادر كل ملك ", reciter: " باسم الكربلائي", poet: " رحيم أبو عليوي الكاظمي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf40.mp3" },
  { id: 41, title: "يمه ذكريني من تمر زفة شباب ", reciter: " حمزة الصغير", poet: " كاظم المنظور الكربلائي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf41.mp3" },
  { id: 42, title: "شلون انساك", reciter: " حمزة الصغير", poet: "المرحوم الشيخ جبار البناء الكربلائي ", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf42.mp3" },
  { id: 43, title: "يمة", reciter: " باسم الكربلائي", poet: " إيهاب المالكي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf43.mp3" },
  { id: 44, title: " مو بس اخو ", reciter: " باسم الكربلائي", poet: "علي السقاي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf44.mp3" },
  { id: 45, title: "  ما ماتت من مرض", reciter: " ذو الفقار الكعبي", poet: "أحمد الهلباوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf45.mp3" },
  { id: 46, title: "مود عينك", reciter: " عمار الكناني", poet: " الحسيني السيد موفق الموسوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf46.mp3" },
  { id: 47, title: " حسيني الهوه", reciter: " كرار ابو غنيم", poet: "قحطان الحسناوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf47.mp3" },
  { id: 48, title: "  الحسين ثورة", reciter: " حسين فيصل", poet: "  خليل آل إسماعيل", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf48.mp3" },
  { id: 49, title: "  جنوني", reciter: " حسين فيصل", poet: "  خليل آل إسماعيل", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf49.mp3" },
  { id: 50, title: "هذا غريب منين  ", reciter: " باسم الكربلائي", poet: "السيد سعيد الصافي الرميثي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf50.mp3" },
  { id: 51, title: "  يوليدي ياعلي", reciter: " سيد حسين الجابري", poet: " كاظم الجابري", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf51.mp3" },
  { id: 52, title: "  علي راح", reciter: " محمد بوجبارة", poet: " أبو تراب الإحسائي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf52.mp3" },
  { id: 53, title: "  حيدريون", reciter: "سيد قاقد ", poet: " سيد محمود الموسوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf53.mp3" },
  { id: 54, title: " قتال العرب", reciter: " سيد فاقد", poet: " سيد محمود الموسوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf54.mp3" },
  { id: 55, title: " ما يحاجيها ", reciter: " حيدر البياتي", poet: "منتظر الجنابي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf55.mp3" },
  { id: 56, title: "  ديوانك حلم كل عاشك", reciter: " مسلم الوائلي و علي الوائلي", poet: " محمد الزيدي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf56.mp3" },
  { id: 57, title: "  اسمعني ارجوك", reciter: "ملسم الزائلي", poet: "حمزة السماوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf57.mp3" },
  { id: 58, title: "  لا ما تطيح راية", reciter: " حيدر البياتي وسيد حسنين الحلو ومصطفى العيساوي", poet: " علي عباس الربيعاوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf58.mp3" },
  { id: 59, title: "  نسيتك", reciter: " باسم الكربلائي", poet: " السيد عبد الخالق المحنة", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf59.mp3" },
  { id: 60, title: "ابجيني مذبوح", reciter: "سيد فاقد", poet: " حمزة الحسناوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf60.mp3" },
  { id: 61, title: "  وينة جمالك", reciter: " حيدر البياتي", poet: " كريم التميمي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf61.mp3" },
  { id: 62, title: " سلام وعن بعظ", reciter: " سيد سلام الحسيني", poet: "أحمد اللامي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf62.mp3" },
  { id: 63, title: "جداه", reciter: "باسم الكربلائي", poet: " حسين العندليب", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf63.mp3" },
  { id: 64, title: "يا بوفاضل", reciter: "باسم الكربلائي", poet: "السيد عبد الخالق المحنة", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf64.mp3" },
  { id: 65, title: "وحدة حسين", reciter: "كرار ابو غنيم", poet: "قحطان الحسناوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf65.mp3" },
  { id: 66, title: "ماضلت عيون", reciter: "كرار ابو غنيم", poet: "قحطان الحسناوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf66.mp3" },
  { id: 67, title: "اجمل ساقي", reciter: " عباس عجيد العامري", poet: "أحمد الهلباوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf67.mp3" },
  { id: 68, title: "  حزن المغريبة", reciter: "عباس عجيد العامري", poet: " هادي شبيب الخيكاني", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf68.mp3" },
  { id: 69, title: "امير حب علي", reciter: " يحيى البنداوي", poet: "سيد أحمد الأعرجي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf69.mp3" },
  { id: 70, title: "3دكات زينب وحسين", reciter: "كرار ابو غنيم", poet: " قحطان الحسناوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf70.mp3" },
  { id: 71, title: "ام وجود", reciter: "يحيى عفارة", poet: "ميثاق الحمداني ", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf71.mp3" },
  { id: 72, title: "مو انة يا حزن", reciter: " سيد سلام الحسيني", poet: "حيدر شايع ", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf72.mp3" },
  { id: 73, title: "يا زينب ", reciter: "باسم الكربلائي", poet: " مهيمن الفاطمي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf73.mp3" },
  { id: 74, title: "بزغ جاسم", reciter: " سيد سلام الحسيني", poet: " منير سعد", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf74.mp3" },
  { id: 75, title: "درب احبابي", reciter: "مرتضى حرب", poet: " مرتضى حرب", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf75.mp3" },
  { id: 76, title: "كلهم مثل عباس", reciter: "مرتضى حرب ", poet: "مرتضى حرب", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf76.mp3" },
  { id: 77, title: "ياعباس ما متت", reciter: "باسم الكربلائي ", poet: " السيد عبدالخالق المحنه", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf77.mp3" },
  { id: 78, title: "اسمع ياعباس", reciter: " حيدر البياتي", poet: " مصطفى العيساوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf78.mp3" },
  { id: 79, title: " ما يتفارك حسين ", reciter: "مرتضى حرب ", poet: " مرتضى حرب", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf79.mp3" },
  { id: 80, title: " رجع عاشور ", reciter: "حيدر البياتي", poet: " أحمد واثق العيساوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf80.mp3" },
  { id: 81, title: "عشت بخيرك", reciter: " محمد الجنامي", poet: "فاضل مقدم", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf81.mp3" },
  { id: 82, title: "على صوتك", reciter: " باسم الكربلائي", poet: " محمد الأعاجيبي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf82.mp3" },
  { id: 83, title: " اهل غيرة", reciter: " سيد فاقد", poet: " محمود الموسوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf83.mp3" },
  { id: 84, title: " اويلي من سمعها حسين ", reciter: " باسم الكربلائي ", poet: " فقط مقطع صوتي صغير ", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf84.mp3" },
  { id: 85, title: "عباس اخويه على النهر 3 دكات ", reciter: "  كرار العارضي", poet: " الملهم عدنان جدي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf85.mp3" },
  { id: 86, title: " ياعلي ", reciter: " احمد الفتلاوي ", poet: "  صباح أمين", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf86.mp3" },
  { id: 87, title: "  يالكافل اخت", reciter: " مرتضى حرب ", poet: " مرتضى حرب  ", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf87.mp3" },
  { id: 88, title: " 3دكات ضنوة الكرار ", reciter: " زيد بقر الشام", poet: " عدنان جدي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf88.mp3" },
  { id: 89, title: "توكل على الله وللنهر  ", reciter: " زيد بقر الشام", poet: "محمد الإبراهيمي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf89.mp3" },
  { id: 90, title: "ليلة العباس ", reciter: " قحطان البديري", poet: " ميثاق الحمداني", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf90.mp3" },
  { id: 91, title: "عافوني كلهم ", reciter: "محمد الحلفي ", poet: " فاضل حسن", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf91.mp3" },
  { id: 92, title: " شيعة علي منصورة", reciter: "سيد سلام الحسيني ", poet: "مرتضى صباح السماوي ", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf92.mp3" },
  { id: 93, title: " هنا يهل العراق ", reciter: "مدين العياشي ", poet: " حسنين سعدي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf93.mp3" },
  { id: 94, title: " وصل عاشورك", reciter: " محمد الجنامي", poet: " حسين الساعي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf94.mp3" },
  { id: 95, title: "  سافرنه", reciter: " محمد الجنامي", poet: " كرار حسين الكربلائي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf95.mp3" },
  { id: 96, title: "كالولي حسين  ", reciter: "سيد فاقد ", poet: " احمد المشرفاوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf96.mp3" },
  { id: 97, title: "طلع ضعن السلام  ", reciter: " سيد فاقد", poet: " حمزة الحسناوي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf97.mp3" },
  { id: 98, title: "فصول الاربعة", reciter: " باسم الكربلائي", poet: " سيد عبدالخالق المحنة", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf98.mp3" },
  { id: 99, title: " موت مهيوب", reciter: "باسم الكربلائي", poet: " علي السقاي", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf99.mp3" },
  { id: 100, title: "  انه ام الراوي", reciter: " باسم الكربلائي", poet: "سيد عبدالخالق المحنة ", file: "https://github.com/kenozero/ritha-al-taff/releases/download/v1.0.0/shuraf100.mp3" }
];
